### PR TITLE
Add Pushover notification option

### PR DESCRIPTION
**Pull request by gcrevell**
This adds a new option for notifications, with [Pushover][po]. It cleans up a bit of the existing code, breaking it apart some to make reuse easier with the new integration.

This also contains a pretty substantial refactor of the way notifications are sent, hopefully allowing new notification paths to be added relatively easily.

[po]: https://pushover.net

### CODE REVIEW

**Comment by gcrevell** [comment]
I decided to clean up the notifications a bit more. Please wait on merging this 👍

**Comment by dgsharpe** [comment]
Thanks for the PR! I'll start looking at this. I noticed you pushed three more commits after your first batch - are you ready for now?

**Comment by gcrevell** [comment]
Yes! I refactored the notifications around a bit

**Comment by dgsharpe** [comment]
This is **seriously** excellent stuff. Thank you for this work!!

There's just one thing noticeable enough to prevent me from merging, which is, there used to be an "enabled" flag on the Mailgun notification config. In your refactor, you've removed that, and it looks like you're expecting the user to remove entire notifier config blocks he or she isn't using. I don't think that's as intuitive to some potential users as simply changing "enabled" to "false". I imagine that some potential users are just barely technically savvy enough to install Linux and follow the README, but may never have written a line of code and may not be sure how to disable an unused notifier without breaking the application. Can you add the enabled flag back in? I'm also happy to merge your PR and then do it myself, just let me know!

**Comment by gcrevell** [comment]
@dgsharpe Understood on the `enabled` key. I added it back in. I did however use the default of `True` so if the key isn't included but the block is (eg. `mailgun: {API: 1234}`) it will still use it. Let me know if you want different default behavior.

**Pull request merged**
